version: "2"

volumes:
  orderer.voting.org:
  peer0.station1.voting.org:
  peer1.station1.voting.org:
  peer0.station2.voting.org:
  peer1.station2.voting.org:
  peer0.station3.voting.org:
  peer1.station3.voting.org:
  peer0.station4.voting.org:
  peer1.station4.voting.org:
  peer0.GovermentAgency.voting.org:
  peer1.GovermentAgency.voting.org:

networks:
  Vnet: # voting network

services:
  orderer.voting.org:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.voting.org
    container_name: orderer.voting.org
    networks:
      - Vnet # voting network

  peer0.station1.voting.org:
    container_name: peer0.station1.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.station1.voting.org
    networks:
      - Vnet

  peer1.station1.voting.org:
    container_name: peer1.station1.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.station1.voting.org
    networks:
      - Vnet

  peer0.station2.voting.org:
    container_name: peer0.station2.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.station2.voting.org
    networks:
      - Vnet

  peer1.station2.voting.org:
    container_name: peer1.station2.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.station2.voting.org
    networks:
      - Vnet

  peer0.station3.voting.org:
    container_name: peer0.station3.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.station3.voting.org
    networks:
      - Vnet

  peer1.station3.voting.org:
    container_name: peer1.station3.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.station3.voting.org
    networks:
      - Vnet

  peer0.station4.voting.org:
    container_name: peer0.station4.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.station4.voting.org
    networks:
      - Vnet

  peer1.station4.voting.org:
    container_name: peer1.station4.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.station4.voting.org
    networks:
      - Vnet

  peer0.GovermentAgency.voting.org:
    container_name: peer0.GovermentAgency.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.GovermentAgency.voting.org
    networks:
      - Vnet

  peer1.GovermentAgency.voting.org:
    container_name: peer1.GovermentAgency.voting.org
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.GovermentAgency.voting.org
    networks:
      - Vnet

  cli:
    container_name: cli
    image: hyperledger/fabric-tools$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.station1.voting.org:7051
      - CORE_PEER_LOCALMSPID=station1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/peers/peer0.station1.voting.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/peers/peer0.station1.voting.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/peers/peer0.station1.voting.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/users/Admin@station1.voting.org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.voting.org
      - peer0.station1.voting.org
      - peer1.station1.voting.org
      - peer0.station2.voting.org
      - peer1.station2.voting.org
      - peer0.station3.voting.org
      - peer1.station3.voting.org
      - peer0.station4.voting.org
      - peer1.station4.voting.org
      - peer0.GovermentAgency.voting.org
      - peer1.GovermentAgency.voting.org
    networks:
      - Vnet
