#!/bin/bash

echo "Installing chaincode"
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/users/Admin@station1.voting.org/msp CORE_PEER_ADDRESS=peer0.station1.voting.org:7051 CORE_PEER_LOCALMSPID="station1MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/peers/peer0.station1.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/users/Admin@station1.voting.org/msp CORE_PEER_ADDRESS=peer1.station1.voting.org:7051 CORE_PEER_LOCALMSPID="station1MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station1.voting.org/peers/peer1.station1.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station2.voting.org/users/Admin@station2.voting.org/msp CORE_PEER_ADDRESS=peer0.station2.voting.org:7051 CORE_PEER_LOCALMSPID="station2MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station2.voting.org/peers/peer0.station2.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station2.voting.org/users/Admin@station2.voting.org/msp CORE_PEER_ADDRESS=peer1.station2.voting.org:7051 CORE_PEER_LOCALMSPID="station2MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station2.voting.org/peers/peer1.station2.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station3.voting.org/users/Admin@station3.voting.org/msp CORE_PEER_ADDRESS=peer0.station3.voting.org:7051 CORE_PEER_LOCALMSPID="station3MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station3.voting.org/peers/peer0.station3.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station3.voting.org/users/Admin@station3.voting.org/msp CORE_PEER_ADDRESS=peer1.station3.voting.org:7051 CORE_PEER_LOCALMSPID="station3MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station3.voting.org/peers/peer1.station3.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station4.voting.org/users/Admin@station4.voting.org/msp CORE_PEER_ADDRESS=peer0.station4.voting.org:7051 CORE_PEER_LOCALMSPID="station4MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station4.voting.org/peers/peer0.station4.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station4.voting.org/users/Admin@station4.voting.org/msp CORE_PEER_ADDRESS=peer1.station4.voting.org:7051 CORE_PEER_LOCALMSPID="station4MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/station4.voting.org/peers/peer1.station4.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/GovermentAgency.voting.org/users/Admin@GovermentAgency.voting.org/msp CORE_PEER_ADDRESS=peer0.GovermentAgency.voting.org:7051 CORE_PEER_LOCALMSPID="GovermentAgencyMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/GovermentAgency.voting.org/peers/peer0.GovermentAgency.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"
sleep .5s
docker exec -ti cli sh -c "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/GovermentAgency.voting.org/users/Admin@GovermentAgency.voting.org/msp CORE_PEER_ADDRESS=peer1.GovermentAgency.voting.org:7051 CORE_PEER_LOCALMSPID="GovermentAgencyMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/GovermentAgency.voting.org/peers/peer1.GovermentAgency.voting.org/tls/ca.crt peer chaincode install -n votingcc -v 1.0 -p chaincode/go/src -l golang"

echo "Instantiating chaincode"
docker exec -ti cli sh -c "peer chaincode instantiate -o orderer.voting.org:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/voting.org/orderers/orderer.voting.org/msp/tlscacerts/tlsca.voting.org-cert.pem -C votingchannel -n votingcc -v 1.0 -c '{\"Args\":[\"Init\",\"Init\", \"Ballot\"]}' -P \"OR ('station1MSP.member','station2MSP.member','station3MSP.member','station4MSP.member','GovermentAgencyMSP.member')\""
